### ISSUE TITLE
 selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:56785

### ISSUE THREAD

**Issue by Angelajzr** [mybdye/H-W#6]
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:56785

**Comment by Angelajzr** [comment]
linux 无桌面模式好像无法使用

**Comment by mybdye** [comment]
GitHub action 跑了`headless=True`没问题，不清楚你的测试环境
https://github.com/mybdye/H-W/blob/66e3b99d710d0828afd6311a0a078c45a59951e4/main.py#L339

**Comment by mybdye** [comment]
> 我是直接在kvm debian 11 下测试 环境是 python3.10

抱歉，我本地无 linux 测试环境，vps 上试了下 debian chrome 的依赖貌似有些问题，没装上，测不了
建议你直接在 GitHub 上小号跑吧。
