### ISSUE TITLE
Multi-Account and Multi-Site Guidelines

### ISSUE THREAD

**Issue by biozzl** [mybdye/H-W#8]
Since it support multiple website i.e. website E and H
The secrets.USER_ID and Pass_WD shall be different from website E and H.
Here is suggestions for enhancement:
1. Is there any plan to support multiple accout?
2. Can it reduce the renew attemps once the successfully renew reuslt obtained? For example, once the successfully renew reuslt obtained, the job will be run after 5 days not daily, in case of extension failure detected, the job will run again in order to obtain success results.

**Comment by MSE5** [comment]
1. For multi-account and multi-site (such as Hxx and Wxx), please refer to `[/.github/workflows/main.yml](https://github.com/mybdye/H-W/edit/main/.github/workflows/main.yml)` settings

**secrets.URL_BASE_H** for website Hxx so you should add a secrets such as `URL_BASE_H`
**secrets.USER_ID_H1** for Hxx account1 so you should add a secret such as `USER_ID_H1`
**secrets.USER_ID_H2** for Hxx account2 so you should add a secret such as `USER_ID_H2`
...
**secrets.URL_BASE_W** for website Wxx so you should add a secrets such as `URL_BASE_W`
...

(My test account is the same, so it keeps the same secrets)

        - name: 'Renew-H'
          env:
            URL_BASE: ${{ secrets.URL_BASE_H }}
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 ./main.py
            
        - name: 'Renew-W'
          env:
            URL_BASE: ${{ secrets.URL_BASE_W }}
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 ./main.py

2. I don't have a lot of study in GitHub action, so I can't implement automatic modification planning. 
But a simple plan can be set `- cron: '03 10 */3 * *'` (UTC 10:03 every three days)

    |    |    |    |    |
    |    |    |    |    +----- day of week (0 - 7) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
    |    |    |    +---------- month (1 - 12) OR jan,feb,mar,apr ...
    |    |    +--------------- day of month (1 - 31)
    |    +-------------------- hour (0 - 23)
    +------------------------- minute (0 - 59)

**Comment by mybdye** [comment]
然后不建议分多个 main.py 和 jobs 执行

**Comment by biozzl** [comment]
Thank you for your guidance
